# Generated by Django 6.1 on 2026-09-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('imagem', models.ImageField(upload_to='destaques/')),
                ('texto_botao', models.CharField(blank=True, max_length=100)),
                ('link_botao', models.URLField(blank=True)),
                ('mostrar_botao', models.BooleanField(default=True)),
                ('posicao_horizontal', models.CharField(choices=[('esquerda', 'Esquerda'), ('centro', 'Centro'), ('direita', 'Direita')], default='esquerda', max_length=20)),
                ('posicao_vertical', models.CharField(choices=[('topo', 'Topo'), ('meio', 'Meio'), ('baixo', 'Baixo')], default='meio', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
