# Generated by Django 6.1 on 2026-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaque',
            name='botao_com_borda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destaque',
            name='botao_italico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destaque',
            name='botao_negrito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='destaque',
            name='botao_sublinhado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destaque',
            name='cor_borda_botao',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='destaque',
            name='cor_fundo_botao',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='destaque',
            name='cor_texto',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='destaque',
            name='cor_texto_botao',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='destaque',
            name='texto_italico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destaque',
            name='texto_negrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destaque',
            name='texto_sublinhado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destaque',
            name='titulo_italico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destaque',
            name='titulo_negrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destaque',
            name='titulo_sublinhado',
            field=models.BooleanField(default=False),
        ),
    ]
