# Generated by Django 6.1 on 2026-09-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0002_destaque_botao_com_borda_destaque_botao_italico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaque',
            name='cor_titulo',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
