# Generated by Django 6.1 on 2026-09-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0003_destaque_cor_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('categoria', models.CharField(choices=[('resultado', 'Resultado'), ('evento', 'Evento'), ('projeto', 'Projeto'), ('novidade', 'Novidade'), ('outros', 'Outros')], max_length=30)),
                ('resumo', models.TextField(max_length=300)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(upload_to='noticias/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('destaque', models.BooleanField(default=False)),
                ('publicada', models.BooleanField(default=True)),
            ],
        ),
    ]
