# Generated by Django 6.1 on 2026-09-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0006_curta_secaocurtas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecaoCurtas',
        ),
        migrations.AlterModelOptions(
            name='curta',
            options={'ordering': ['ordem'], 'verbose_name': 'Curta em destaque', 'verbose_name_plural': 'Curtas em destaque'},
        ),
        migrations.RenameField(
            model_name='curta',
            old_name='capa',
            new_name='cartaz',
        ),
        migrations.RemoveField(
            model_name='curta',
            name='titulo',
        ),
        migrations.AddField(
            model_name='curta',
            name='cor_borda',
            field=models.CharField(default='#8B2FF7', max_length=7),
        ),
    ]
