# Generated by Django 6.1 on 2026-09-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0007_delete_secaocurtas_alter_curta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoCurtas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='CURTAS EM DESTAQUE', max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Texto da seção de curtas',
                'verbose_name_plural': 'Texto da seção de curtas',
            },
        ),
    ]
