# Generated by Django 6.1 on 2026-09-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0008_secaocurtas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curta',
            name='cor_borda',
        ),
        migrations.AddField(
            model_name='curta',
            name='cor_borda_1',
            field=models.CharField(default='#7C3AED', max_length=7),
        ),
        migrations.AddField(
            model_name='curta',
            name='cor_borda_2',
            field=models.CharField(default='#06B6D4', max_length=7),
        ),
    ]
