# Generated by Django 6.1 on 2026-09-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0009_remove_curta_cor_borda_curta_cor_borda_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='PRONTO PARA DAR VIDA ÀS SUAS IDEIAS?', max_length=200)),
                ('subtitulo', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Texto da seção final',
                'verbose_name_plural': 'Texto da seção final',
            },
        ),
    ]
