# Generated by Django 6.1 on 2026-09-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0010_secaofinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='secaofinal',
            name='link_botao',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='secaofinal',
            name='texto_botao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
