# Generated by Django 6.1 on 2026-09-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0011_secaofinal_link_botao_secaofinal_texto_botao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrilhasCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Ex: INSCRIÇÃO DAS EQUIPES', max_length=100)),
                ('titulo', models.CharField(help_text='Ex: Toda grande produção começa com uma boa equipe.', max_length=250)),
                ('descricao', models.TextField(help_text='Ex: Conheça a ficha de inscrição, apresente sua equipe...')),
                ('tipo_icone', models.CharField(choices=[('equipes', 'Aperto de mão (Equipes)'), ('texto', 'Livro aberto (Texto Autoral)'), ('roteiro', 'Lápis (Roteiro)'), ('personalizado', 'Imagem / SVG personalizado')], default='equipes', help_text='Selecione o ícone ilustrado padrão ou envie uma imagem própria', max_length=30)),
                ('icone_personalizado', models.ImageField(blank=True, help_text='Opcional. Imagem ou SVG caso tenha selecionado ícone personalizado', null=True, upload_to='trilhas/icones/')),
                ('mostrar_botao', models.BooleanField(default=True)),
                ('texto_botao', models.CharField(blank=True, default='Explorar trilha', max_length=100)),
                ('link_botao', models.CharField(blank=True, default='/trilhas/visao-geral/', max_length=255)),
                ('cor_fundo_card', models.CharField(default='#EBF1E8', help_text='Cor de fundo do card', max_length=7)),
                ('cor_borda_card', models.CharField(default='#141414', help_text='Cor da borda do card', max_length=7)),
                ('estilo_borda', models.CharField(choices=[('dashed', 'Tracejada'), ('solid', 'Sólida'), ('dotted', 'Pontilhada'), ('none', 'Sem borda')], default='dashed', max_length=20)),
                ('cor_glow', models.CharField(default='#EA580C', help_text='Cor do brilho neon no fundo do card', max_length=7)),
                ('cor_tag', models.CharField(default='#1E293B', help_text='Cor da tag superior', max_length=7)),
                ('cor_titulo', models.CharField(default='#0F172A', help_text='Cor do título', max_length=7)),
                ('cor_descricao', models.CharField(default='#475569', help_text='Cor da descrição', max_length=7)),
                ('cor_fundo_botao', models.CharField(default='#000000', help_text='Cor de fundo do botão', max_length=7)),
                ('cor_texto_botao', models.CharField(default='#FFFFFF', help_text='Cor do texto do botão', max_length=7)),
                ('tag_negrito', models.BooleanField(default=True)),
                ('tag_italico', models.BooleanField(default=False)),
                ('titulo_negrito', models.BooleanField(default=True)),
                ('titulo_italico', models.BooleanField(default=True)),
                ('descricao_negrito', models.BooleanField(default=False)),
                ('descricao_italico', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trilhas - Card de Trilha',
                'verbose_name_plural': 'Trilhas - Cards de Trilhas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TrilhasFaixaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Ex: 5 ETAPAS, DEZENAS DE MATERIAIS, EXERCÍCIOS, EXEMPLOS REAIS', max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trilhas - Item da Faixa Informativa',
                'verbose_name_plural': 'Trilhas - Itens da Faixa Informativa',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TrilhasHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Bem-Vindo(a)', max_length=200)),
                ('subtitulo', models.TextField(blank=True, default='Aprenda produção audiovisual em módulos práticos e criativos.')),
                ('imagem_fundo', models.ImageField(blank=True, help_text='Opcional. Se não enviada, mantém o fundo escuro com iluminação neon.', null=True, upload_to='trilhas/hero/')),
                ('mostrar_botao', models.BooleanField(default=True)),
                ('texto_botao', models.CharField(blank=True, default='Conheça as trilhas', max_length=100)),
                ('link_botao', models.CharField(blank=True, default='/trilhas/visao-geral/', max_length=255)),
                ('cor_titulo', models.CharField(default='#FFFFFF', max_length=7)),
                ('cor_subtitulo', models.CharField(default='#FFFFFF', max_length=7)),
                ('cor_fundo_botao', models.CharField(default='#FFFFFF', max_length=7)),
                ('cor_texto_botao', models.CharField(default='#0B0C10', max_length=7)),
                ('cor_glow_1', models.CharField(default='#7C3AED', help_text='Cor primária do brilho neon central', max_length=7)),
                ('cor_glow_2', models.CharField(default='#22D3EE', help_text='Cor secundária do brilho neon central', max_length=7)),
                ('titulo_negrito', models.BooleanField(default=True)),
                ('titulo_italico', models.BooleanField(default=False)),
                ('subtitulo_negrito', models.BooleanField(default=False)),
                ('subtitulo_italico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trilhas - Seção de Boas-Vindas (Hero)',
                'verbose_name_plural': 'Trilhas - Seção de Boas-Vindas (Hero)',
            },
        ),
    ]
