# Generated by Django 6.1 on 2026-09-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0012_trilhascard_trilhasfaixaitem_trilhashero'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='cor_fundo_destaque',
            field=models.CharField(default='#B6495F', help_text='Cor de fundo exibida na seção de destaque (só é usada quando "destaque" estiver marcado).', max_length=7),
        ),
    ]
