# Generated by Django 6.1 on 2026-09-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0013_noticia_cor_fundo_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destaque_secundario',
            field=models.BooleanField(default=False, help_text='Aparece na seção de destaques abaixo dos posts recentes. Não entra mais na lista de "Últimas notícias".'),
        ),
    ]
