# Generated by Django 6.1 on 2026-09-22 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0016_alter_noticia_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilhascard',
            name='imagem_capa',
            field=models.ImageField(blank=True, help_text='Imagem de capa ilustrativa do card da trilha', null=True, upload_to='trilhas/capas/'),
        ),
        migrations.AlterField(
            model_name='trilhascard',
            name='cor_borda_card',
            field=models.CharField(default='#1E2659', help_text='Cor da borda do card', max_length=7),
        ),
        migrations.AlterField(
            model_name='trilhascard',
            name='cor_descricao',
            field=models.CharField(default='#CBD5E1', help_text='Cor da descrição', max_length=7),
        ),
        migrations.AlterField(
            model_name='trilhascard',
            name='cor_fundo_botao',
            field=models.CharField(default='#B94B61', help_text='Cor de fundo do botão', max_length=7),
        ),
        migrations.AlterField(
            model_name='trilhascard',
            name='cor_fundo_card',
            field=models.CharField(default='#101535', help_text='Cor de fundo do card', max_length=7),
        ),
        migrations.AlterField(
            model_name='trilhascard',
            name='cor_glow',
            field=models.CharField(default='#7C3AED', help_text='Cor do brilho neon no fundo do card', max_length=7),
        ),
        migrations.AlterField(
            model_name='trilhascard',
            name='cor_tag',
            field=models.CharField(default='#94A3B8', help_text='Cor da tag superior', max_length=7),
        ),
        migrations.AlterField(
            model_name='trilhascard',
            name='cor_titulo',
            field=models.CharField(default='#FFFFFF', help_text='Cor do título', max_length=7),
        ),
        migrations.AlterField(
            model_name='trilhascard',
            name='estilo_borda',
            field=models.CharField(choices=[('dashed', 'Tracejada'), ('solid', 'Sólida'), ('dotted', 'Pontilhada'), ('none', 'Sem borda')], default='solid', max_length=20),
        ),
        migrations.AlterField(
            model_name='trilhascard',
            name='texto_botao',
            field=models.CharField(blank=True, default='Começar', max_length=100),
        ),
        migrations.AlterField(
            model_name='trilhascard',
            name='titulo_italico',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubtopicoTrilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do item/subtópico. Ex: CONTO e CRÔNICA: como diferenciar?', max_length=255)),
                ('link', models.CharField(blank=True, default='', help_text='Link específico para o material ou aula (opcional). Se vazio, usará o link da trilha.', max_length=255)),
                ('mostrar_botao_comecar', models.BooleanField(default=False, help_text='Exibir o botão "Começar" ao lado deste item')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='rede_miradas.trilhascard')),
            ],
            options={
                'verbose_name': 'Subtópico da Trilha',
                'verbose_name_plural': 'Subtópicos da Trilha',
                'ordering': ['ordem'],
            },
        ),
    ]
