# Generated by Django 6.1 on 2026-09-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0017_trilhascard_imagem_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilhascard',
            name='tipo_icone',
            field=models.CharField(choices=[('equipes', 'Aperto de mão (Equipes)'), ('texto', 'Livro aberto (Texto Autoral)'), ('roteiro', 'Lápis (Roteiro)'), ('producao', 'Câmera de Cinema (Produção e Gravação)'), ('edicao', 'Ilha de Edição e Corte (Edição e Finalização)'), ('personalizado', 'Imagem / SVG personalizado')], default='equipes', help_text='Selecione o ícone ilustrado padrão ou envie uma imagem própria', max_length=30),
        ),
    ]
