# Generated by Django 6.1 on 2026-09-24 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0018_alter_trilhascard_tipo_icone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurtaVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartaz', models.ImageField(upload_to='votacao/')),
                ('titulo', models.CharField(max_length=200)),
                ('grupo', models.CharField(max_length=150, verbose_name='Nome do grupo')),
                ('turma', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Curta em votação',
                'verbose_name_plural': 'Curtas em votação',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_voto', models.DateTimeField(auto_now_add=True)),
                ('curta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='rede_miradas.curtavotacao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
        migrations.DeleteModel(
            name='CodigoProfessor',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('comum', 'Usuário comum')], max_length=20),
        ),
    ]
