# Generated by Django 6.1 on 2026-09-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0018_alter_trilhascard_tipo_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cor_fundo_destaque',
            field=models.CharField(default='#3A1660', help_text='Cor de fundo exibida na seção de destaque (só é usada quando "destaque" estiver marcado).', max_length=7),
        ),
    ]
