# Generated by Django 6.1 on 2026-09-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0019_curtavotacao_voto_delete_codigoprofessor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='perfil',
            name='curtas_favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='rede_miradas.curta'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='escola',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='grupo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Grupo/equipe'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='link_curta_participou',
            field=models.URLField(blank=True, verbose_name='Link do YouTube do meu curta'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='link_outra_rede',
            field=models.URLField(blank=True, verbose_name='Outra rede social / portfólio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_curta_participou',
            field=models.CharField(blank=True, max_length=200, verbose_name='Curta que participei'),
        ),
    ]
