# Generated by Django 6.1 on 2026-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0020_perfil_bio_perfil_curtas_favoritos_perfil_escola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_curta_participou',
            field=models.ImageField(blank=True, null=True, upload_to='curtas_usuarios/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='logo_grupo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_grupos/'),
        ),
    ]
