# Generated by Django 6.1 on 2026-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0021_perfil_foto_curta_participou_perfil_logo_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners_perfil/'),
        ),
    ]
