# Generated by Django 6.1 on 2026-09-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0022_perfil_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='curta',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=200),
        ),
    ]
