# Generated by Django 6.1 on 2026-09-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0023_curta_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='curta',
            name='grupo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do grupo'),
        ),
    ]
