# Generated by Django 6.1 on 2026-09-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0019_alter_noticia_cor_fundo_destaque'),
        ('rede_miradas', '0024_curta_grupo'),
    ]

    operations = [
    ]
