# Generated by Django 6.1 on 2026-09-26 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0025_merge_20260926_1443'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('imagem', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Insígnia',
                'verbose_name_plural': 'Insígnias',
            },
        ),
        migrations.CreateModel(
            name='InsigniaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conquistada_em', models.DateTimeField(auto_now_add=True)),
                ('aviso_confirmado', models.BooleanField(default=False)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='rede_miradas.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insígnia do usuário',
                'verbose_name_plural': 'Insígnias dos usuários',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'insignia'), name='usuario_insignia_unica')],
            },
        ),
    ]
