# Generated by Django 6.1 on 2026-09-26 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0026_insignia_insigniausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Selo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Identificador usado no código para conceder esse selo. Ex: primeiro-login, primeiro-voto', unique=True)),
                ('descricao', models.CharField(help_text='Texto curto explicando como o selo é conquistado.', max_length=200)),
                ('imagem', models.ImageField(upload_to='selos/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Selo',
                'verbose_name_plural': 'Selos',
            },
        ),
        migrations.CreateModel(
            name='SeloConquistado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('visualizado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Selo conquistado',
                'verbose_name_plural': 'Selos conquistados',
                'ordering': ['-data_conquista'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='insigniausuario',
            name='usuario_insignia_unica',
        ),
        migrations.AddField(
            model_name='seloconquistado',
            name='selo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_miradas.selo'),
        ),
        migrations.AddField(
            model_name='seloconquistado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selos_conquistados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='insigniausuario',
            name='insignia',
        ),
        migrations.RemoveField(
            model_name='insigniausuario',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='seloconquistado',
            unique_together={('usuario', 'selo')},
        ),
        migrations.DeleteModel(
            name='Insignia',
        ),
        migrations.DeleteModel(
            name='InsigniaUsuario',
        ),
    ]
