# Generated by Django 6.1 on 2026-09-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0027_selo_seloconquistado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seloconquistado',
            name='selo',
            field=models.SlugField(help_text='Identificador do selo, definido em rede_miradas/selos.py'),
        ),
        migrations.DeleteModel(
            name='Selo',
        ),
    ]
