# Generated by Django 6.1 on 2026-09-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0025_merge_20260926_2049'),
        ('rede_miradas', '0028_alter_seloconquistado_selo_delete_selo'),
    ]

    operations = [
    ]
