# Generated by Django 6.1 on 2026-09-30 00:12

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_miradas', '0029_merge_20260927_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilhascard',
            name='cor_sidebar',
            field=models.CharField(default='#8F3D4E', help_text='Cor de fundo da barra lateral na página de detalhes', max_length=7),
        ),
        migrations.AddField(
            model_name='trilhascard',
            name='cor_sidebar_topo',
            field=models.CharField(default='#BA586C', help_text='Cor de fundo do box superior da barra lateral', max_length=7),
        ),
        migrations.AddField(
            model_name='trilhascard',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único da URL da trilha, ex: inscricao-das-equipes', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trilhascard',
            name='titulo_detalhe',
            field=models.CharField(blank=True, default='', help_text='Título exibido no topo da página de detalhes (ex: INSCRIÇÃO DAS EQUIPES: IDENTIDADE VISUAL)', max_length=250),
        ),
        migrations.CreateModel(
            name='UnidadeTrilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Número da Unidade (ex: 1, 2, 3...)')),
                ('titulo', models.CharField(help_text='Nome da unidade (ex: Identidade Visual ou Conto e Crônica)', max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='rede_miradas.trilhascard')),
            ],
            options={
                'verbose_name': 'Trilhas - Unidade da Trilha',
                'verbose_name_plural': 'Trilhas - Unidades das Trilhas',
                'ordering': ['ordem', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='TopicoUnidadeTrilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do tópico/subtópico (ex: Identidade visual da equipe: como fazer?)', max_length=250)),
                ('conteudo', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Conteúdo (Texto / Formatação)')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='rede_miradas.unidadetrilha')),
            ],
            options={
                'verbose_name': 'Trilhas - Tópico / Conteúdo da Unidade',
                'verbose_name_plural': 'Trilhas - Tópicos / Conteúdos das Unidades',
                'ordering': ['ordem'],
            },
        ),
    ]
